### ISSUE TITLE
05_zfs_linux.py fails with AttributeError

### ISSUE THREAD

**Issue by thornmir** [johnramsden/zedenv-grub#24]
Hi ,
While running only grub-mkconfig I get this output :
```
### BEGIN /etc/grub.d/05_zfs_linux.py ###
Traceback (most recent call last):
  File "/etc/grub.d/05_zfs_linux.py", line 839, in <module>
    for en in Generator().generate_grub_entries():
  File "/etc/grub.d/05_zfs_linux.py", line 676, in generate_grub_entries
    key=functools.cmp_to_key(Generator.kernel_comparator))
  File "/etc/grub.d/05_zfs_linux.py", line 775, in kernel_comparator
    if sv0 < sv1:
  File "/usr/local/lib/python3.7/distutils/version.py", line 64, in __gt__
    c = self._cmp(other)
  File "/usr/local/lib/python3.7/distutils/version.py", line 170, in _cmp
    if self.version != other.version:
AttributeError: 'int' object has no attribute 'version'
```

**Comment by johnramsden** [comment]
What are the versions of `zedenv` and `zedenv-grub` you are using?

**Comment by thornmir** [comment]
Master branch for both. I checked git pull just now.

EDIT : __init__.py from zedenv :
```
# __init__.py

import subprocess

__version__ = '0.3.6'


def vcs_release(version: str):
    """
    If in git repo, get git version
    """
    try:
        git_hash = subprocess.check_output(
            ['git', 'rev-parse', '--short', 'HEAD'],
            universal_newlines=True, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError:
        return version

    return version + '+git.' + git_hash

```

__init__.py from zedenv-grub : 
```
# __init__.py

__version__ = '0.1.6'

```

**Comment by johnramsden** [comment]
Ahh, I think I see the problem.Do you mind checking the following fixes the issue?

Line 765 of `/etc/grub.d/05_zfs_linux.py`

```
diff --git a/grub.d/05_zfs_linux.py b/grub.d/05_zfs_linux.py
index 571f6e4..a2e0bdd 100755
--- a/grub.d/05_zfs_linux.py
+++ b/grub.d/05_zfs_linux.py
@@ -765,11 +765,11 @@ class Generator:
                 sv1 = -1
                 try:
                     sv0 = StrictVersion(version0.group(1))
-                except ValueError:
+                except (ValueError, AttributeError, TypeError):
                     pass
                 try:
                     sv1 = StrictVersion(version1.group(1))
-                except ValueError:
+                except (ValueError, AttributeError, TypeError):
                     pass
 
                 if sv0 < sv1:
```

**Comment by johnramsden** [comment]
Also, what is your kernel named? Can you print the output of `ls /boot/`?

**Comment by thornmir** [comment]
After patch i get exactly the same error. 
Output of `uname -a` : `Linux ns352801.ip-37-187-138.eu 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Output  of `cat /etc/redhat-release` : `CentOS Linux release 7.6.1810 (Core) `
Output of `ls /boot` : 
```
total 113244
-rw-------. 1 root root  3544010 Nov 29 15:53 System.map-3.10.0-957.1.3.el7.x86_64
-rw-------. 1 root root  3543471 Nov  9 00:43 System.map-3.10.0-957.el7.x86_64
-rw-r--r--. 1 root root   151922 Nov 29 15:53 config-3.10.0-957.1.3.el7.x86_64
-rw-r--r--. 1 root root   151918 Nov  9 00:43 config-3.10.0-957.el7.x86_64
drwxr-xr-x. 2 root root        3 Jan 21 15:07 flask
drwxr-xr-x. 2 root root        3 Jan 20 19:54 grub
drwx------. 5 root root       13 Jan 22 16:52 grub2
-rw-------. 1 root root 53878696 Jan 17 18:45 initramfs-0-rescue-804508375bda4cc7ad8fa26c09d979f1.img
-rw-------. 1 root root 19879720 Jan 18 15:31 initramfs-3.10.0-957.1.3.el7.x86_64.img
-rw-------. 1 root root 19884478 Jan 18 15:34 initramfs-3.10.0-957.el7.x86_64.img
-rw-r--r--. 1 root root   314072 Nov 29 15:53 symvers-3.10.0-957.1.3.el7.x86_64.gz
-rw-r--r--. 1 root root   314036 Nov  9 00:43 symvers-3.10.0-957.el7.x86_64.gz
-rwxr-xr-x. 1 root root  6639904 Jan 17 18:45 vmlinuz-0-rescue-804508375bda4cc7ad8fa26c09d979f1
-rwxr-xr-x. 1 root root  6639808 Nov 29 15:53 vmlinuz-3.10.0-957.1.3.el7.x86_64
-rwxr-xr-x. 1 root root  6639904 Nov  9 00:43 vmlinuz-3.10.0-957.el7.x86_64
```

**Comment by johnramsden** [comment]
Okay I think this should fix it. Do you mind trying the patch below, or installing from the https://github.com/johnramsden/zedenv-grub/commit/6d6a996393990ff007062b8627746844b89483f5 branch?

```
diff --git a/grub.d/05_zfs_linux.py b/grub.d/05_zfs_linux.py
index 571f6e4..5452213 100755
--- a/grub.d/05_zfs_linux.py
+++ b/grub.d/05_zfs_linux.py
@@ -9,7 +9,7 @@ import pyzfscmds.utility
 import re
 import subprocess
 import functools
-from distutils.version import StrictVersion
+from distutils.version import LooseVersion
 
 import zedenv.lib.be
 import zedenv.lib.check
@@ -764,19 +764,22 @@ class Generator:
                 sv0 = -1
                 sv1 = -1
                 try:
-                    sv0 = StrictVersion(version0.group(1))
+                    sv0 = LooseVersion(version0.group(1))
                 except ValueError:
                     pass
                 try:
-                    sv1 = StrictVersion(version1.group(1))
+                    sv1 = LooseVersion(version1.group(1))
                 except ValueError:
                     pass
 
-                if sv0 < sv1:
-                    return -1
-                if sv0 == sv1:
+                try:
+                    if sv0 < sv1:
+                        return -1
+                    if sv0 == sv1:
+                        return ext_cmp(kernel0, kernel1)
+                    return 1
+                except AttributeError:
                     return ext_cmp(kernel0, kernel1)
-                return 1
 
             if version0:
                 return 1
```

**Comment by thornmir** [comment]
Patching fixed the issue. Thank you !
